### ISSUE TITLE
props 中的 schema 也会被解析

### ISSUE THREAD

**Issue by gonglixin980926** [alibaba/x-render#717]
**1.依赖仓库的版本(Dependencies versions)**：

- react：^17.0.2
- form-render：^1.9.9
- table-render: 
- antd：^4.15.0

**2.问题描述(Bug description)**：
TypeError: Cannot read properties of undefined (reading 'optionType')
    at eval (eval at parseSingleExpression (utils.js:505:1), <anonymous>:4:221)
    at parseSingleExpression (utils.js:505:1)
    at utils.js:555:1
    at Array.forEach (<anonymous>)
    at parseAllExpression (utils.js:549:1)
    at utils.js:553:1
    at Array.forEach (<anonymous>)
    at parseAllExpression (utils.js:549:1)
    at utils.js:553:1
    at Array.forEach (<anonymous>)
    at parseAllExpression (utils.js:549:1)
    at utils.js:553:1
    at Array.forEach (<anonymous>)
    at parseAllExpression (utils.js:549:1)
    at utils.js:553:1
    at Array.forEach (<anonymous>)
    at parseAllExpression (utils.js:549:1)
    at utils.js:553:1
    at Array.forEach (<anonymous>)
    at parseAllExpression (utils.js:549:1)
    at utils.js:553:1
    at Array.forEach (<anonymous>)
    at parseAllExpression (utils.js:549:1)
    at utils.js:553:1
    at Array.forEach (<anonymous>)
    at parseAllExpression (utils.js:549:1)
    at utils.js:553:1
    at Array.forEach (<anonymous>)
    at parseAllExpression (utils.js:549:1)
    at utils.js:553:1
    at Array.forEach (<anonymous>)
    at parseAllExpression (utils.js:549:1)
    at useForm.js:172:1
    at Array.forEach (<anonymous>)
    at useForm.js:160:1
    at invokePassiveEffectCreate (react-dom.development.js:23487:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at flushPassiveEffectsImpl (react-dom.development.js:23574:1)
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushPassiveEffects (react-dom.development.js:23447:1)
    at react-dom.development.js:23324:1
    at workLoop (scheduler.development.js:417:1)
    at flushWork (scheduler.development.js:390:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:157:1)

![image](https://user-images.githubusercontent.com/40887236/160360783-168e2987-880c-478a-bf13-0b944ae96b05.png)

**3.最小复现 demo(Reproduction demo)**：
在 props 中传递一个 schema，会被解析导致报错。

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by siyi98** [comment]
贴下你的代码看看

**Comment by gonglixin980926** [comment]
没问题了
