### ISSUE TITLE
本地 link form-render 报错

### ISSUE THREAD

**Issue by gonglixin980926** [alibaba/x-render#845]
**1.依赖仓库的版本(Dependencies versions)**：

- react：^17.0.2
- form-render：^1.9.5
- table-render: 
- antd：

**2.问题描述(Bug description)**：
1. fork x-render
2. 根目录 yarn && yarn build
3. x-render/packages/form-render  yarn link
4. 个人项目 yarn link form-render && yarn start

在进行以上操作后，便出现如下错误
`Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
5. You might be breaking the Rules of Hooks
6. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (react.development.js:1476:1)
    at useState (react.development.js:1507:1)
    at useForm (useForm.js:47:1)
    at CustomForm (index.tsx:71:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at mountIndeterminateComponent (react-dom.development.js:17811:1)
    at beginWork (react-dom.development.js:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
react-dom.development.js:20085 The above error occurred in the <CustomForm> component:

    at CustomForm (http://localhost:3001/static/js/bundle.js:341:68)
    at Routes (http://localhost:3001/static/js/bundle.js:48991:5)
    at div
    at App
    at Router (http://localhost:3001/static/js/bundle.js:48924:15)
    at HashRouter (http://localhost:3001/static/js/bundle.js:47768:5)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:20085
bootstrap:27 Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (react.development.js:1476:1)
    at useState (react.development.js:1507:1)
    at useForm (useForm.js:47:1)
    at CustomForm (index.tsx:71:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at mountIndeterminateComponent (react-dom.development.js:17811:1)
    at beginWork (react-dom.development.js:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)`

**3.最小复现 demo(Reproduction demo)**：
[space](https://github.com/gonglixin980926/space)

form-render demo https://codesandbox.io/s/unruffled-flower-jl78h
table-render demo https://codesandbox.io/s/sweet-euler-bdoty
fr-generator demo https://codesandbox.io/s/s13sh

**Comment by gonglixin980926** [comment]
如在 app.tsx 中使用 HashRouter、Switch、ReduxProvider、Route 组件也会报出如下错误
![image](https://user-images.githubusercontent.com/40887236/177714450-b4197469-e84d-427a-b2ca-edfed9f6ee3a.png)

**Comment by siyi98** [comment]
用 lerna link 试试

**Comment by gonglixin980926** [comment]
> 用 lerna link 试试

刚刚试了下，在x-render 根目录 lerna link
然后在进入form-render 目录进行 yarn link 还以有错误

**Comment by gonglixin980926** [comment]
我把项目fork 了下来，只保留了form-render 组件，进行link，依然是有错误

**Comment by gonglixin980926** [comment]
![image](https://user-images.githubusercontent.com/40887236/178469699-045b1d37-ffed-41c3-a8be-a605cc4d3d11.png)
改一下版本就好了

**Comment by siyi98** [comment]
> 依然是

报的什么错误，截图看看

**Comment by gonglixin980926** [comment]
> > 依然是
> 
> 报的什么错误，截图看看
![image](https://user-images.githubusercontent.com/40887236/178639172-78e532c2-82d9-4c7b-99b0-a92e536d4368.png)
![image](https://user-images.githubusercontent.com/40887236/178639204-89697d43-51c7-4f88-a394-48d1e1087ecc.png)
这个错误的原因是同时存在了两个react 实例，我用了 https://github.com/wclr/yalc 这个东西给解决了
不过本地调试还是有点麻烦，每次都需要 yalc push 下
