### ISSUE TITLE
引入fr-generator打包报错SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by Superbsco** [alibaba/x-render#930]
**1.依赖仓库的版本(Dependencies versions)**：

```
  "@babel/plugin-proposal-class-properties": "^7.4.0",
    "@babel/plugin-proposal-decorators": "^7.4.0",
    "@types/react-swf": "0.0.33",
    "@zeit/next-css": "1.0.1",
    "@zeit/next-less": "^1.0.1",
    "@zeit/next-sass": "1.0.1",
    "@zeit/next-typescript": "1.1.1",
    "antd": "4.16.1",
    "app-base-react": "^3.3.80",
    "babel-loader": "^8.2.5",
    "babel-plugin-import": "1.11.0",
    "cross-env": "5.0.5",
    "echarts": "4.3.0",
    "express": "4.16.4",
    "form-render": "^1.13.14",
    "fr-generator": "^2.8.0",
    "http-proxy-middleware": "0.19.1",
    "increase-memory-limit": "1.0.3",
    "js-cookie": "2.2.0",
    "less": "^4.1.3",
    "mobx": "5.9.4",
    "mobx-react": "5.4.3",
    "next": "^8.0.4",
    "next-compose-plugins": "^2.1.1",
    "next-offline": "^3.3.8",
    "node-sass": "5.0.0",
    "nodemon": "2.0.4",
    "prop-types": "15.7.2",
    "query-string": "6.2.0",
    "react": "^16.14.0",
    "react-dom": "^16.14.0",
    "react-window": "^1.8.6",
    "sass-loader": "10.1.1",
    "@babel/preset-react": "^7.12.1",
    "qs": "6.9.4",
    "react-router-dom": "5.2.0"
```

**2.问题描述(Bug description)**：
打包报错：
```
 /var/lib/jenkins/workspace/UAT_app-shenyang-admin/node_modules/antd/es/config-provider/style/index.js:1
22:46:22 import './index.less';
22:46:22 ^^^^^^
22:46:22 
22:46:22 SyntaxError: Cannot use import statement outside a module
22:46:22     at compileFunction (<anonymous>)
22:46:22     at wrapSafe (internal/modules/cjs/loader.js:979:16)
22:46:22     at Module._compile (internal/modules/cjs/loader.js:1027:27)
22:46:22     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
22:46:22     at Module.load (internal/modules/cjs/loader.js:928:32)
22:46:22     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
22:46:22     at Module.require (internal/modules/cjs/loader.js:952:19)
22:46:22     at require (internal/modules/cjs/helpers.js:88:18)
22:46:22     at Object.<anonymous> (/var/lib/jenkins/workspace/UAT_app-shenyang-admin/node_modules/form-render/lib/index.js:40:1)
22:46:22     at Module._compile (internal/modules/cjs/loader.js:1063:30)
22:46:22     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
22:46:22     at Module.load (internal/modules/cjs/loader.js:928:32)
22:46:22     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
22:46:22     at Module.require (internal/modules/cjs/loader.js:952:19)
22:46:22     at require (internal/modules/cjs/helpers.js:88:18)
22:46:22     at Object.ybbo (/var/lib/jenkins/workspace/UAT_app-shenyang-admin/.next/server/static/KYS1eq1NStnmwtNK9mB_2/pages/generator/Provider.js:2258:18)
22:46:22 error Command failed with exit code 1.
```

**.babel配置**
```
{
  "presets": [
    "next/babel", "@babel/preset-react" 
  ],
  "plugins": [
    ["@babel/plugin-proposal-decorators", {
      "legacy": true
    }],
    ["@babel/plugin-proposal-class-properties", {
      "loose": true
    }],
    [
      "import",
      {
        "libraryName": "antd",
        "style": "css"
      },
      "antd"
    ],
    [
      "import",
      {
        "libraryName": "app-base-react",
        "libraryDirectory": "lib/library",
        "style": true
      }
    ]
  ]
}
```

**next.config.js配置**
```

const withPlugins = require('next-compose-plugins')
const withTypescript = require('@zeit/next-typescript')
const withSass = require('@zeit/next-sass')
const withLess = require('@zeit/next-less')
const withCss = require('@zeit/next-css')
const withOffline = require('next-offline')
const {resolve} = require('path')

if (typeof require !== 'undefined') {
  require.extensions['.css'] = file => {}
}

const nextConfig = {
  env: {
    _ENV: process.env._ENV
  },
  lessLoaderOptions: {
    modifyVars: {
      // 'primary-color': '#1DA57A'
    },
    javascriptEnabled: true
  },
  webpack: (config, options) => {
    // Further custom webpack configuration here
    config.resolve.alias['@']=resolve(__dirname)
    // config.module.rules.forEach(rule => {
    //   if (rule && rule.test) {
    //     // .css 不使用 modules
    //     const rTest = rule.test.toString();
    //     if (rTest.includes('.css')) {
    //       rule.use.forEach((useRule, i) => {
    //         if (useRule.loader && useRule.loader.includes('css-loader')) {
    //           rule.use[i] = {
    //             ...useRule,
    //             options: {
    //               ...useRule.options,
    //               modules: true,
    //             },
    //           };
    //         }
    //       });
    //     }
    //   }
    // });
    // console.log('config %o',config)
    return config;
  },
  workboxOpts: {
    //workbox custom
  }
};

module.exports = withPlugins([
  // add plugins here..
  [withTypescript],
  [withSass],
  [withLess],
  [withCss],
  [withOffline]
], nextConfig);

```

**Comment by Superbsco** [comment]
感觉是配置babel问题？百度了很久没有找到解决办法，前来求助

**Comment by Superbsco** [comment]
我自己解决了，在此记录一下，看看能不能帮到有缘人，主要是form-render这个包的问题，把schema-gengrator这个包和form-render这个包的src单独拿出来，schema-gengrator里面引了form-render，然后把loadsh-es替换成loadsh，再把smoth-scroll去掉，改成node.scrollIntoView({behavior: "smooth", block: "end", inline: "nearest"})就可以了

**Comment by wx9999** [comment]
> 我自己解决了，在此记录一下，看看能不能帮到有缘人，主要是form-render这个包的问题，把schema-generator这个包和form-render这个包的src单独拿出来，schema-generator里面引了form-render，然后把loadsh-es替换成loadsh，再把smooth-scroll去掉，改成node.scrollIntoView({behavior: "smooth", block: "end", inline: "nearest"})就可以了。
> 
> 在此猜测原因估计是我的架构不支持es6打包，目测改babel是可以解决的，奈何水平不够，同时抠出来src修改源码符合我的业务需求，就先这样了。

我也遇到了此类问题，还没找到解决方法，可否交流一下
